version = 0.1
[default.deploy.parameters]
stack_name = "web-list-sample-app"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true

#resolve_s3 = true
#s3_prefix = "logisticmodel"
#image_repositories = []
